#!/bin/bash
#load config
source scalarm_registration_config
#script
if [ -z "$INFORMATION_SERVICE_URL" ]; then
    INFORMATION_SERVICE_URL=$INFORMATION_SERVICE_URL_CONFIG
fi
if [ -z "$INFORMATION_SERVICE_LOGIN" ]; then
    INFORMATION_SERVICE_LOGIN=$INFORMATION_SERVICE_LOGIN_CONFIG
fi
if [ -z "$INFORMATION_SERVICE_PASSWORD" ]; then
    INFORMATION_SERVICE_PASSWORD=$INFORMATION_SERVICE_PASSWORD_CONFIG
fi  
curl -u $INFORMATION_SERVICE_LOGIN:$INFORMATION_SERVICE_PASSWORD --data "address=$REMOTE_LOAD_BALANCER_ADDRESS" http://$INFORMATION_SERVICE_URL/experiment_managers
echo
curl -u $INFORMATION_SERVICE_LOGIN:$INFORMATION_SERVICE_PASSWORD --data "address=$REMOTE_LOAD_BALANCER_ADDRESS/storage" http://$INFORMATION_SERVICE_URL/storage_managers
echo
curl -k --data "address=$INFORMATION_SERVICE_URL&name=InformationService" https://$LOCAL_LOAD_BALANCER_ADDRESS/register
echo
